### ISSUE TITLE
希望能够支持项目配置识别目录

### ISSUE THREAD

**Issue by manson-2020** [crazyurus/miniprogram-vscode-extension#19]
类似uniapp和taro这类框架， 都会编译后生成一个小程序文件目录， 希望能加入配置直接进行识别。

**Comment by crazyurus** [comment]
插件支持在 `project.config.json` 中配置 `miniprogramRoot` 指定上传目录，也可以直接右键文件夹选择【设置为编译上传目录】。
附文档：https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html

**Comment by crazyurus** [comment]
`1.4.5` 增加了对这种情况的支持
