### ISSUE TITLE
模拟器启动后，显示一片白，除了顶栏

### ISSUE THREAD

**Issue by Sanzro-Lee** [crazyurus/miniprogram-vscode-extension#20]
平台：macOS 10.15.4
小程序框架：Mpx。编译出来的内容，微信小程序开发工具可正常识别。
扫码预览小程序功能正常。
![image](https://user-images.githubusercontent.com/46492606/102915593-05198b80-44bd-11eb-8225-b68f52e4cd55.png)

**Comment by cuevven** [comment]
vscode 无法预览这问题要怎么解决？

**Comment by Sanzro-Lee** [comment]
> vscode 无法预览这问题要怎么解决？

它能生成二维码，我是用实机扫描二维码暂时解决，但那时我是想着用iPad开发的，有电脑的情况下还是开微信开发者工具吧。

**Comment by cuevven** [comment]
> > vscode 无法预览这问题要怎么解决？
> 
> 它能生成二维码，我是用实机扫描二维码暂时解决，但那时我是想着用iPad开发的，有电脑的情况下还是开微信开发者工具吧。

看来只能用微信开发者工具了。感谢你的回复。

**Comment by Sanzro-Lee** [comment]
> > > vscode 无法预览这问题要怎么解决？
> 
> > 
> 
> > 它能生成二维码，我是用实机扫描二维码暂时解决，但那时我是想着用iPad开发的，有电脑的情况下还是开微信开发者工具吧。
> 
> 
> 
> 看来只能用微信开发者工具了。感谢你的回复。
不客气，也有可能是因为我用了MPX这个框架，但是它最终编译的代码也是符合微信的标准的，还是用微信开发者工具吧

**Comment by Sanzro-Lee** [comment]
> > > vscode 无法预览这问题要怎么解决？
> 
> > 
> 
> > 它能生成二维码，我是用实机扫描二维码暂时解决，但那时我是想着用iPad开发的，有电脑的情况下还是开微信开发者工具吧。
> 
> 
> 
> 看来只能用微信开发者工具了。感谢你的回复。

不客气，也有可能是因为我用了MPX这个框架，但是它最终编译的代码也是符合微信的标准的，还是用微信开发者工具吧
