### ISSUE TITLE
子目录作为微信小程序的工作目录

### ISSUE THREAD

**Issue by Arsennnic** [crazyurus/miniprogram-vscode-extension#22]
您好@crazyurus. 我遇到的问题类似 Issue #19.
我的工程目录包含server和client两部分, 微信小程序作为我的客户端, 源码放在client子目录下. 工程目录类似于:
```
root
├ .vscode
│  └ settings.json
├ client
│  ├ pages/index
│  │  ├ index.js
│  │  ├ index.json
│  │  ├ index.wxml
│  │  └ index.wxss
│  ├ app.js
│  ├ app.json
│  ├ app.wxss
│  └ project.config.json
└ server
```

如果我在根目录root下打开vscode, 会报错并提示:
```
Command 'MiniProgram: 预览小程序' resulted in an error (command 'MiniProgram.commands.compile.preview' not found)
```

请问我该如何指定client子目录为微信小程序的工作目录? 可以通过.vscode/setting.json完成配置吗?

**Comment by crazyurus** [comment]
`project.config.json` 是否可以移动到根目录下，按照微信官方的文档推荐采用 `miniprogramRoot` 指定小程序项目目录，插件也是按这个规范支持的 https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html
