### ISSUE TITLE
 ENOENT: no such file or directory, open 微信开发者工具

### ISSUE THREAD

**Issue by Ricky-yy** [crazyurus/miniprogram-vscode-extension#29]
是否可以设置小程序的路径？

**Comment by Ricky-yy** [comment]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/35446079/175471638-3e4310dd-b02b-4a18-a95f-10943f23e1f8.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/35446079/175471677-03bc3a5b-51f0-4722-adc2-b79f94c04898.png">
设置了没用

**Comment by crazyurus** [comment]
不需要在图1的位置配置，这个配置项是用来指定小程序代码目录的
麻烦看看图2报错的路径是否存在

**Comment by Ricky-yy** [comment]
> 

图2路径并不存在

**Comment by crazyurus** [comment]
可能是计算微信 IDE 的路径这块逻辑有点问题，晚点我排查下。可以先手动打开。

**Comment by Ricky-yy** [comment]
> 可能是计算微信 IDE 的路径这块逻辑有点问题，晚点我排查下。可以先手动打开。

感谢！
我现在的困惑是vscode无法调微信开发者工具，其他暂无问题。

**Comment by Ricky-yy** [comment]
> 可能是计算微信 IDE 的路径这块逻辑有点问题，晚点我排查下。可以先手动打开。

解决了，是因为微信IDE安全设置没打开

**Comment by crazyurus** [comment]
[56273880bbce494905fda7f2e9cda75240a2a7c2](https://github.com/crazyurus/miniprogram-vscode-extension/commit/56273880bbce494905fda7f2e9cda75240a2a7c2)
