### ISSUE TITLE
小程序代码上传密钥文件怎么下载

### ISSUE THREAD

**Issue by Leon-zym** [crazyurus/miniprogram-vscode-extension#31]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/17230055/177677261-909aad60-2ff4-420d-ae9d-614d1f9146cb.png">

在vscode中使用插件需要选择一个文件作为代码上传的密钥，可是我在小程序后台管理页面的 开发管理-开发设置-小程序代码上传 里面只有重置密钥选项，并会得到一串AppSecret，只能复制其密钥的文本，并没有下载文件的选项啊……

---

![image](https://user-images.githubusercontent.com/17230055/177677937-4477876a-91fe-460e-a028-2b3ad4053c8a.png)

**Comment by crazyurus** [comment]
显示 **重置** 说明之前已经生成过密钥文件，需要点击重置重新生成，生成后之前的会失效

**Comment by crazyurus** [comment]
@Leon-zym 我刚才试了下重置会得到一个 **下载密钥** 的链接（小程序代码上传这个区域），你是不是重置错了点成了上面的 AppSecret 重置

**Comment by Leon-zym** [comment]
> @Leon-zym 我刚才试了下重置会得到一个 **下载密钥** 的链接（小程序代码上传这个区域），你是不是重置错了点成了上面的 AppSecret 重置

还真是！哎呀我草率了哈哈
