### ISSUE TITLE
代码补全如何工作

### ISSUE THREAD

**Issue by Shane-Peterson** [crazyurus/miniprogram-vscode-extension#36]
代码补全是如何工作的，你可以举个例子吗？
非常感谢！！

**Comment by crazyurus** [comment]
代码补全有多种场景，实现方式也不太一样：
- wxml：通过 language server 实现
- wx api ：通过加载 ts 类型，以及代码片段
- json：通过 json schema
具体实现可以看看 package.json 中的配置
