### ISSUE TITLE
希望可以增加自定义小程序IDE路径配置字段

### ISSUE THREAD

**Issue by chenbimo** [crazyurus/miniprogram-vscode-extension#37]
![image](https://user-images.githubusercontent.com/33003566/205418630-ff761536-8aea-44a1-9bb7-98dde31c9400.png)

如上图，IDE在D盘。

![image](https://user-images.githubusercontent.com/33003566/205418654-724bb8d8-5545-4932-a312-83009b5c861a.png)

提示找不到IDE。

**Comment by crazyurus** [comment]
收到，Windows 应该可以从注册表读到安装路径，后续版本优化下

**Comment by chenbimo** [comment]
> 

建议做个配置项，这样兼容性更好，可以面对更多不同的路径。

**Comment by crazyurus** [comment]
#41
