### ISSUE TITLE
vscode不显示小程序操作面板了

### ISSUE THREAD

**Issue by chenbimo** [crazyurus/miniprogram-vscode-extension#43]
![image](https://user-images.githubusercontent.com/33003566/206367644-6bfd5220-8f7c-4ea8-a1dd-628e06f15edf.png)

切换到1.4.13是正常的。

![image](https://user-images.githubusercontent.com/33003566/206367677-b53950db-bf7d-4ee5-ab74-2ed1d5201ba0.png)

**Comment by crazyurus** [comment]
`1.4.14` 构建脚本有点问题，已经在发新版了

**Comment by crazyurus** [comment]
`1.4.15` 已发布，可以试下指定 IDE 路径的功能

**Comment by chenbimo** [comment]
> `1.4.15` 已发布，可以试下指定 IDE 路径的功能

已经可以了，但是另外一个问题出现了。😂

![image](https://user-images.githubusercontent.com/33003566/206376116-fe358880-b96b-4a2f-88f0-c6625f83f6bf.png)

端口开启了也没用。

**Comment by chenbimo** [comment]
问题基本清楚了，回头空了再提个PR。

**Comment by chenbimo** [comment]
配置已经打开了，我觉得，是那个status文件地址的问题，我在电脑上没找到那个路径。

![image](https://user-images.githubusercontent.com/33003566/206378547-8300ab74-29f6-4579-b049-bdb641a83d79.png)

**Comment by crazyurus** [comment]
Get 了，可能是自定义安装路径后 status 的位置也有变化。欢迎再次 PR

**Comment by chenbimo** [comment]
> 

好的。

**Comment by chenbimo** [comment]
顺便说一句，为了尽快解决这个问题，我已经重新安装到C盘了。🤔
