### ISSUE TITLE
左下角打开微信开发者工具时提示服务端口已关闭，但是明明是开着的。

### ISSUE THREAD

**Issue by ygqygq2** [crazyurus/miniprogram-vscode-extension#44]
如图：
![image](https://user-images.githubusercontent.com/17672440/219241255-8bb92cec-b276-49db-b341-51c8e33ad5e8.png)

![image](https://user-images.githubusercontent.com/17672440/219241378-a73c0d5e-b4a2-448e-947f-cf85b18c04b5.png)

**Comment by ZhaoYuCoco** [comment]
请问你解决了吗？

**Comment by ygqygq2** [comment]
> 请问你解决了吗？

没有，只能手动打开了。

**Comment by crazyurus** [comment]
收到，这个问题我跟进下

**Comment by crazyurus** [comment]
@ZhaoYuCoco @ygqygq2 已修复，麻烦更新到 1.4.16

**Comment by ZhaoYuCoco** [comment]
> @ZhaoYuCoco @ygqygq2 已修复，麻烦更新到 1.4.16

这边OK了
