### ISSUE TITLE
上传小程序代码报错

### ISSUE THREAD

**Issue by ZhaoYuCoco** [crazyurus/miniprogram-vscode-extension#45]
![20230418112614](https://user-images.githubusercontent.com/127492123/232664396-49ec1b9c-0ce0-421f-9fcf-03081a0c9c24.png)
![20230418113426](https://user-images.githubusercontent.com/127492123/232664411-6ae4495b-4497-4bd3-88bd-875fdcf04833.png)
如图，上次更新后上传成功。今天重新加载更新后，上传失败。

**Comment by crazyurus** [comment]
可能是因为你的 IP 地址变了，建议直接在微信后台关掉 IP 白名单功能

**Comment by laamfun** [comment]
检查下 `project.config.json` 里的 APPID ，这里不能使用测试号的 id

**Comment by iamphc** [comment]
> 检查下 `project.config.json` 里的 APPID ，这里不能使用测试号的 id

我爱死你了，老哥。谢谢谢谢谢！
