### ISSUE TITLE
json文件警告：Incorrect type. Expected "object".

### ISSUE THREAD

**Issue by lihanspace** [crazyurus/miniprogram-vscode-extension#47]
![image](https://github.com/crazyurus/miniprogram-vscode-extension/assets/60546798/1c806132-1406-4358-b216-d8eecbf9b4ca)
当json文件里最上层是array的时候，插件会给出警告

**Comment by crazyurus** [comment]
确实有点问题，这个 schema 应该只作用于小程序相关的 JSON 文件校验，我看下如何修复

**Comment by toFrankie** [comment]
+1

**Comment by crazyurus** [comment]
@lihanspace @toFrankie 已修复，请更新到 1.4.17
