### ISSUE TITLE
预览小程序失败

### ISSUE THREAD

**Issue by YaoJuan** [crazyurus/miniprogram-vscode-extension#59]
是不是我的文件目录出了问题，可是我是用小程序的ide建的默认demo。
报错信息如下
<img width="478" alt="image" src="https://github.com/crazyurus/miniprogram-vscode-extension/assets/16183272/c8d751a3-f0d7-433a-9549-94d02c814259">
<img width="553" alt="image" src="https://github.com/crazyurus/miniprogram-vscode-extension/assets/16183272/9267aec8-1079-4151-b595-1dcfe77049cc">

**Comment by crazyurus** [comment]
是因为目前 `miniprogram-ci` 还不支持 TypeScript 的编译导致的，已到官方社区反馈

https://developers.weixin.qq.com/community/minihome/doc/00046490d24928267d81b45eb61c00

**Comment by YaoJuan** [comment]
> 是因为目前 `miniprogram-ci` 还不支持 TypeScript 的编译导致的，已到官方社区反馈
> 
> https://developers.weixin.qq.com/community/minihome/doc/00046490d24928267d81b45eb61c00

OK,小程序团队也是服了。。23年就有人提issue了。到现在还没人解决

**Comment by crazyurus** [comment]
小程序团队增加了 `useProjectConfig` 选项，现在支持编译 TypeScript 了

**Comment by Kline-x** [comment]
> 小程序团队增加了 `useProjectConfig` 选项，现在支持编译 TypeScript 了。可以更新到 1.5.1

更新到 1.5.1还是不行
