### ISSUE TITLE
启动模拟器提示：指定目录不存在或者不是目录，请检查

### ISSUE THREAD

**Issue by chatterzhao** [crazyurus/miniprogram-vscode-extension#8]
怎么指定目录？我打开的就是项目根目录，一个上线了的小程序，不存在编译错误

**Comment by crazyurus** [comment]
逻辑是会优先读取 `project.config.json` 下的 `miniprogramRoot` 字段，如果是空的话读取项目根目录，可以 check 一下是否存在这个字段

**Comment by chatterzhao** [comment]
![image](https://user-images.githubusercontent.com/11829944/79937067-85e63a80-848b-11ea-819f-e5982ec497af.png)

**Comment by crazyurus** [comment]
忘了解析相对路径，我补一下

**Comment by crazyurus** [comment]
感谢反馈，1.3.5 已修复
