### ISSUE TITLE
使用上传密钥一直报错

### ISSUE THREAD

**Issue by veecam** [crazyurus/miniprogram-vscode-extension#9]
![微信图片_20200426115714](https://user-images.githubusercontent.com/3665456/80297410-38343f80-87b5-11ea-9571-1df2d85658be.png)
文件是存在的。

**Comment by crazyurus** [comment]
感谢反馈，`Windows` 下路径处理有点问题，麻烦更新到 `1.3.6` 再点击插件面板中的清除缓存，再试一下上传
